version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    # Keep data
    volumes:
       - db_data:/var/lib/mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    deploy:
      replicas: 1

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    networks:
      - back
    deploy:
      replicas: 1

volumes:
  db_data:
networks:
  back: