version: '3.7'

services:
  wordpress:
    image: wordpress
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    deploy:
      replicas: 2

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
volumes:
  db_data:

